services:
  ielts_training_app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: ielts_training_app
    container_name: ielts_training_app
    network_mode: "host"
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRED: ${JWT_ACCESS_TOKEN_EXPIRED}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_TOKEN_EXPIRED: ${JWT_REFRESH_TOKEN_EXPIRED}
      MAILER_USER: ${MAILER_USER}
      MAILER_PASSWORD: ${MAILER_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALL_BACK_URL: ${GOOGLE_CALL_BACK_URL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      NODE_ENV: development
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    ports:
      - '3000:3000'
    volumes:
      - ./src:/src
      - ./prisma:/prisma
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    network_mode: "host"
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data: